version: '2.3'
services:
 xubuntu:
  hostname: xubuntu.urawski.com
  image: uraf/ubuntu-xfce-x2go
  restart: always
  dns_search: urawski.com
  ports:
   - 4000:4000/tcp
   - 2222:22/tcp
  environment:
  - DOCKER_USER=uraf
  - DOCKER_PASSWORD=uraf
  - DOCKER_USER_ID=1001
  volumes:
  - /home/uraf/code:/data/code
  - ./tmp:/tmp/temp
  cap_add:
  - NET_ADMIN
  - SYS_PTRACE
